name: build-linux-x86_64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: select gcc 10
      run: |
        sudo update-alternatives \
            --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 \
            --slave /usr/bin/g++ g++ /usr/bin/g++-10 \
            --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-10 \
            --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-10 \
            --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-10 \
            --slave /usr/bin/gcov gcov /usr/bin/gcov-10 \
            --slave /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-10 \
            --slave /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-10
    - uses: actions/checkout@v3
    - name: Install prerequisite
      run: sudo apt-get install ninja-build
    - name: configure
      run: cmake --preset linux-gcc
    - name: make
      run: cmake --build build/linux-gcc
